Repository CMPUT301F21T36/OldHabitsDieHard, pull requests merged in 2021-11, with the labels that each got.

#70 Intent activity testing
  app/build.gradle
  app/src/androidTest/java/com/example/oldhabitsdiehard/FollowingActivityTest.java
  app/src/androidTest/java/com/example/oldhabitsdiehard/LoginActivityTest.java
  app/src/androidTest/java/com/example/oldhabitsdiehard/ProfileActivityTest.java
  app/src/androidTest/java/com/example/oldhabitsdiehard/TodayActivityTest.java
  app/src/main/res/layout/activity_login.xml
Labels: test

#71 Habit tests
  .idea/misc.xml
  app/src/main/java/com/example/oldhabitsdiehard/Habit.java
  app/src/test/java/com/example/oldhabitsdiehard/HabitTest.java
  app/src/test/java/com/example/oldhabitsdiehard/UserTest.java
Labels: test

#76 fixed weird habit bug
  app/src/main/java/com/example/oldhabitsdiehard/Habit.java
Labels: bug

#75 fixed weird habit bug
  app/src/main/java/com/example/oldhabitsdiehard/Habit.java
Labels: bug

#108 fixed search nonexistent user bug
  app/src/main/java/com/example/oldhabitsdiehard/SearchActivity.java
Labels: bug

#111 following habit click
  .idea/misc.xml
  app/src/main/java/com/example/oldhabitsdiehard/FollowingHabitFragment.java
  app/src/main/java/com/example/oldhabitsdiehard/SearchActivity.java
  app/src/main/java/com/example/oldhabitsdiehard/SearchAdapter.java
  app/src/main/res/layout/following_habit_fragment.xml
Labels: Base

#109 added rules for habit title and delete image when it is edited
  app/src/main/java/com/example/oldhabitsdiehard/HabitEventFragment.java
  app/src/main/java/com/example/oldhabitsdiehard/HabitFragment.java
Labels: bug

#117 Javadoc
  .idea/misc.xml
  app/src/main/java/com/example/oldhabitsdiehard/CreateAccount.java
  app/src/main/java/com/example/oldhabitsdiehard/EditProfileActivity.java
  app/src/main/java/com/example/oldhabitsdiehard/FollowRequest.java
  app/src/main/java/com/example/oldhabitsdiehard/FollowRequestAdapter.java
  app/src/main/java/com/example/oldhabitsdiehard/FollowerActivity.java
  app/src/main/java/com/example/oldhabitsdiehard/FollowerAdapter.java
  app/src/main/java/com/example/oldhabitsdiehard/FollowingActivity.java
  app/src/main/java/com/example/oldhabitsdiehard/FollowingAdapter.java
  app/src/main/java/com/example/oldhabitsdiehard/FollowingHabitFragment.java
  app/src/main/java/com/example/oldhabitsdiehard/Habit.java
  app/src/main/java/com/example/oldhabitsdiehard/HabitAdapter.java
  app/src/main/java/com/example/oldhabitsdiehard/HabitEvent.java
  app/src/main/java/com/example/oldhabitsdiehard/HabitEventAdapter.java
  app/src/main/java/com/example/oldhabitsdiehard/HabitEventFragment.java
  app/src/main/java/com/example/oldhabitsdiehard/HabitEventListActivity.java
  app/src/main/java/com/example/oldhabitsdiehard/HabitFragment.java
  app/src/main/java/com/example/oldhabitsdiehard/HabitListActivity.java
  app/src/main/java/com/example/oldhabitsdiehard/Login.java
  app/src/main/java/com/example/oldhabitsdiehard/MyMapView.java
  app/src/main/java/com/example/oldhabitsdiehard/ProfileActivity.java
  app/src/main/java/com/example/oldhabitsdiehard/SearchActivity.java
  app/src/main/java/com/example/oldhabitsdiehard/SearchAdapter.java
  app/src/main/java/com/example/oldhabitsdiehard/TodayActivity.java
  app/src/main/java/com/example/oldhabitsdiehard/TodayHabitAdapter.java
  app/src/main/java/com/example/oldhabitsdiehard/User.java
  app/src/main/java/com/example/oldhabitsdiehard/UserDatabase.java
Labels: Base

#119 added comments to new files and removed some obsolete functions
  app/src/main/java/com/example/oldhabitsdiehard/FollowingUserActivity.java
  app/src/main/java/com/example/oldhabitsdiehard/HabitEvent.java
  app/src/main/java/com/example/oldhabitsdiehard/StaticHabitAdapter.java
  app/src/test/java/com/example/oldhabitsdiehard/HabitEventTest.java
  app/src/test/java/com/example/oldhabitsdiehard/HabitTest.java
  app/src/test/java/com/example/oldhabitsdiehard/UserTest.java
Labels: Base

#121 Updated comments
  app/src/androidTest/java/com/example/oldhabitsdiehard/CreateAccountTest.java
  app/src/androidTest/java/com/example/oldhabitsdiehard/EditProfileActivityTest.java
  app/src/androidTest/java/com/example/oldhabitsdiehard/ExampleInstrumentedTest.java
  app/src/androidTest/java/com/example/oldhabitsdiehard/FollowerActivityTest.java
  app/src/androidTest/java/com/example/oldhabitsdiehard/FollowingActivityTest.java
  app/src/androidTest/java/com/example/oldhabitsdiehard/HabitEventListActivityTest.java
  app/src/androidTest/java/com/example/oldhabitsdiehard/HabitListActivityTest.java
  app/src/androidTest/java/com/example/oldhabitsdiehard/LoginActivityTest.java
  app/src/androidTest/java/com/example/oldhabitsdiehard/ProfileActivityTest.java
  app/src/androidTest/java/com/example/oldhabitsdiehard/TodayActivityTest.java
Labels: documentation
